### ISSUE TITLE
Blank AES Key and Bitcoin Key(s) returned

### ISSUE THREAD

**Issue by VirusD** [Googulator/TeslaCrack#7] opened 2015-12-28 18:07 UTC
Cannot decrypt D:\Downloads\Web\TeslaCrack-master\Test Files\sid077\2/Master 15.12.15.xls.vvv, unknown key
Software has encountered the following unknown AES keys, please crack them first using msieve:
found in D:\Downloads\Web\TeslaCrack-master\Test Files\sid077\2/Master 15.12.15.xls.vvv
Alternatively, you can crack the following Bitcoin key(s) using msieve, and use them with TeslaDecoder:
found in D:\Downloads\Web\TeslaCrack-master\Test Files\sid077\2/Master 15.12.15.xls.vvv
![untitled](https://cloud.githubusercontent.com/assets/16466509/12023096/110d5cdc-ad64-11e5-9dac-7a22248e55c9.png)

**Comment by TamaBaka** [comment] 2015-12-28 19:12
I'm pretty certain that a sample file is needed here, because it looks like nonprintable characters are being shown.  i.e. the keys got moved to a different location in the file / the keys are not stored in the file anymore.

**Comment by VirusD** [comment] 2015-12-28 19:16
Sure, here is the sample file:

[Master 15.12.15.xls.vvv.zip](https://github.com/Googulator/TeslaCrack/files/73471/Master.15.12.15.xls.vvv.zip)

**Comment by TamaBaka** [comment] 2015-12-28 19:44
From address 0x0000000000 up until 0x000029FFFF, that entire section has been zeroed out.  I'm not sure if it's padding or data destruction.

I didn't see any hints of the keys as well.

**Comment by VirusD** [comment] 2015-12-28 19:51
Seeing as how I already have the decryption key, applied and verified that it was correct for them, is there some way I could force the decryption on this file to see what the presumed file error/corruption turns out to be?

**Comment by TamaBaka** [comment] 2015-12-28 20:21
Not sure.  I leave that for someone smarter than I.

**Comment by VirusD** [comment] 2015-12-28 20:26
I found two other files, unrelated to the first, where teslacrack.py only displays part of the public key. It appears to be missing two characters and thus I'm getting the wrong factors in subsequent steps.
[pippo.zip](https://github.com/Googulator/TeslaCrack/files/73526/pippo.zip)

**Comment by msalvini** [comment] 2015-12-28 22:04
Good evening , I also have been infected by teslacrypt .vvv , I did all the procedures I installed python 2.11 , http : //www.voidspace.org.uk/python/pycrypto-2.6.1/pycrypto-2.6.1-cp27 -none - win_amd64.whl , python -c "import urllib2 ; urllib2.urlopen print ( ' https://bootstrap.pypa.io/ez_setup.py ' ) .read ( ) " | python
easy_install pip everything goes well then I put my files .vvv I launched from the command prompt with administrator privileges python teslacrack.py this answer and I do not know if this is the right public key and the second because if you can use by then the command msieve : run msieve -v -e < public key from teslacrack.py > I get an error that I do not know how to solve .

C:\ggnfs>python teslacrack.py
Cannot decrypt ./cipas.doc.vvv, unknown key
Cannot decrypt ./msieve/IMPRESE.doc.vvv, unknown key
Software has encountered the following unknown AES keys, please crack them first
 using msieve:
097AE3032C33E55B89202DF8933FAAB54A5B411381626C84C9CD5CED79250FEA43FB2969C5174A14
6D8F62DE91FD8B2B5FAE21857C6D79A34438A06976F2A9A8 found in ./cipas.doc.vvv
Alternatively, you can crack the following Bitcoin key(s) using msieve, and use
them with TeslaDecoder:
487CC3BFEC11CD25A2D0AD5D235AAFD36EED9AF3B0458B829A81F8D6ED6670917CE89A41B00EA66A
CE9D0F80E26460788F004806ACF1FD4C5B85A6C387DA5C6C found in ./cipas.doc.vvv

if there someone who can help me thank you in advance

**Comment by msalvini** [comment] 2015-12-28 22:08
Sorry I forgot the error on the public key using msieve 

C:\ggnfs>msieve -v -e 097AE3032C33E55B89202DF8933FAAB54A5B411381626C84C9CD5CED79
250FEA43FB2969C5174A146D8F62DE91FD8B2B5FAE21857C6D79A34438A06976F2A9A8
error 0 converting '097AE3032C33E55B89202DF8933FAAB54A5B411381626C84C9CD5CED7925
0FEA43FB2969C5174A146D8F62DE91FD8B2B5FAE21857C6D79A34438A06976F2A9A8'

**Comment by Googulator** [comment] 2015-12-28 22:08
You need to add 0x before the key to let msieve know it's hexadecimal.

**Comment by msalvini** [comment] 2015-12-28 22:25
Ok , it's working thank you help me write the next command ?
I have to use unfactor.py or unfactor-ecdsa.py ? and if you've already made ​​the recovery procedure make me an example of the steps 

6 Run python unfactor.py <name of encrypted file> <primes from previous step, separated by spaces> to reconstruct 
7 Edit teslacrack.py, and add your public and private AES keys to the known_keys array.
9 Run python teslacrack.py C:\ from an administrator command prompt to decrypt your files.

thank you, you already know were recovered files

**Comment by msalvini** [comment] 2015-12-28 22:26
C:\ggnfs>msieve -v -e 097AE3032C33E55B89202DF8933FAAB54A5B411381626C84C9CD5CED79
250FEA43FB2969C5174A146D8F62DE91FD8B2B5FAE21857C6D79A34438A06976F2A9A8
error 0 converting '097AE3032C33E55B89202DF8933FAAB54A5B411381626C84C9CD5CED7925
0FEA43FB2969C5174A146D8F62DE91FD8B2B5FAE21857C6D79A34438A06976F2A9A8'

C:\ggnfs>msieve -v -e 0x097AE3032C33E55B89202DF8933FAAB54A5B411381626C84C9CD5CED
79250FEA43FB2969C5174A146D8F62DE91FD8B2B5FAE21857C6D79A34438A06976F2A9A8

Msieve v. 1.52 (SVN 939)
Mon Dec 28 23:15:04 2015
random seeds: 17a49078 2df94488
factoring 4965092718782766729742712715534238391203658067553364022691835994219984
22397620497557942631772228552491146882785842882555772068583002473431556523621001
640 (153 digits)
searching for 15-digit factors
P-1 stage 2 factor found
searching for 20-digit factors
searching for 25-digit factors
200 of 214 curves
completed 214 ECM curves
commencing quadratic sieve (90-digit input)
using multiplier of 5
using VC8 32kb sieve core
sieve interval: 36 blocks of size 32768
processing polynomials in batches of 6
using a sieve bound of 1615891 (61176 primes)
using large prime bound of 135734844 (27 bits)
using double large prime bound of 435355802910756 (42-49 bits)
using trial factoring cutoff of 49 bits
polynomial 'A' values have 12 factors

sieving in progress (press Ctrl-C to pause)
1650 relations (1536 full + 114 combined from 62733 partial), need 61272

is now working I have a seven i5 64bit should end soon .

**Comment by msalvini** [comment] 2015-12-28 22:40
python unfactor.py <name of encrypted file> <primes from previous step, separated by spaces>

This command does not understand it , I just have to put the name of the file ?
<primes from previous step ???? 
separated by spaces> ????

This command does not understand it , I just have to put the name of the file ? fields are to be valued ? and with what?
and with what? I'm going crazy is from 30/11/2016 I'm looking for a solution to recover my files !

**Comment by msalvini** [comment] 2015-12-28 22:46
python unfactor.py <name of encrypted file> <primes from previous step, separated by spaces>
                                                                                        ^                                  ^
                                                                                        |                                   |

**Comment by Googulator** [comment] 2015-12-28 22:47
E.g. <code>python unfactor.py cipas.doc.vvv 2 2 2 2 3 3 5 7 11 11</code>

**Comment by msalvini** [comment] 2015-12-28 23:07
2 2 2 2 3 3 5 7 11 11 are the factors found 

It gives msieve -e -v when will end ' to work .
I put them all P or P1 only ?

**Comment by Googulator** [comment] 2015-12-28 23:45
You will need to put all "P" and "PRP" factors there. If a factor is printed multiple times by msieve, put it the same number of times on the command line.

E.g.
p1 = 2
p1 = 2
prp6 = 379009
prp6 = 379009
prp6 = 379009

becomes

<code>python unfactor.py cipas.doc.vvv 2 2 379009 379009 379009</code>

A good way to check: the numbers on the command line, when multiplied up and converted to hex, should yield the AES public key from teslacrack.py

**Comment by msalvini** [comment] 2015-12-29 00:04
C:\ggnfs>msieve -v -e 097AE3032C33E55B89202DF8933FAAB54A5B411381626C84C9CD5CED79
250FEA43FB2969C5174A146D8F62DE91FD8B2B5FAE21857C6D79A34438A06976F2A9A8
error 0 converting '097AE3032C33E55B89202DF8933FAAB54A5B411381626C84C9CD5CED7925
0FEA43FB2969C5174A146D8F62DE91FD8B2B5FAE21857C6D79A34438A06976F2A9A8'

C:\ggnfs>msieve -v -e 0x097AE3032C33E55B89202DF8933FAAB54A5B411381626C84C9CD5CED
79250FEA43FB2969C5174A146D8F62DE91FD8B2B5FAE21857C6D79A34438A06976F2A9A8

Msieve v. 1.52 (SVN 939)
Mon Dec 28 23:15:04 2015
random seeds: 17a49078 2df94488
factoring 4965092718782766729742712715534238391203658067553364022691835994219984
22397620497557942631772228552491146882785842882555772068583002473431556523621001
640 (153 digits)
searching for 15-digit factors
P-1 stage 2 factor found
searching for 20-digit factors
searching for 25-digit factors
200 of 214 curves
completed 214 ECM curves
commencing quadratic sieve (90-digit input)
using multiplier of 5
using VC8 32kb sieve core
sieve interval: 36 blocks of size 32768
processing polynomials in batches of 6
using a sieve bound of 1615891 (61176 primes)
using large prime bound of 135734844 (27 bits)
using double large prime bound of 435355802910756 (42-49 bits)
using trial factoring cutoff of 49 bits
polynomial 'A' values have 12 factors

sieving in progress (press Ctrl-C to pause)
61618 relations (16187 full + 45431 combined from 670278 partial), need 61272
61618 relations (16187 full + 45431 combined from 670278 partial), need 61272
sieving complete, commencing postprocessing
begin with 686465 relations
reduce to 151468 relations in 10 passes
attempting to read 151468 relations
recovered 151468 relations
recovered 132159 polynomials
attempting to build 61618 cycles
found 61618 cycles in 5 passes
distribution of cycle lengths:
   length 1 : 16187
   length 2 : 11572
   length 3 : 10810
   length 4 : 8256
   length 5 : 5949
   length 6 : 3804
   length 7 : 2288
   length 9+: 2752
largest cycle: 19 relations
matrix is 61176 x 61618 (15.9 MB) with weight 3685877 (59.82/col)
sparse part has weight 3685877 (59.82/col)
filtering completed in 3 passes
matrix is 57454 x 57518 (14.9 MB) with weight 3452460 (60.02/col)
sparse part has weight 3452460 (60.02/col)
saving the first 48 matrix rows for later
matrix includes 64 packed rows
matrix is 57406 x 57518 (9.5 MB) with weight 2692576 (46.81/col)
sparse part has weight 1917967 (33.35/col)
using block size 8192 and superblock size 589824 for processor cache size 6144 k
B
commencing Lanczos iteration
memory use: 6.0 MB

C:\ggnfs>

He said msieve went wrong , but I do not know if it is blocked I finished the procedure , you see my factors found ??

**Comment by msalvini** [comment] 2015-12-29 00:07
Mon Dec 28 22:15:15 2015  
Mon Dec 28 22:15:15 2015  
Mon Dec 28 22:15:15 2015  Msieve v. 1.52 (SVN 939)
Mon Dec 28 22:15:15 2015  random seeds: 37bfa7fc 71c36984
Mon Dec 28 22:15:15 2015  factoring 487 (3 digits)
Mon Dec 28 22:15:15 2015  p3 factor: 487
Mon Dec 28 22:15:15 2015  elapsed time 00:00:00
Mon Dec 28 23:15:04 2015  
Mon Dec 28 23:15:04 2015  
Mon Dec 28 23:15:04 2015  Msieve v. 1.52 (SVN 939)
Mon Dec 28 23:15:04 2015  random seeds: 17a49078 2df94488
Mon Dec 28 23:15:04 2015  factoring 496509271878276672974271271553423839120365806755336402269183599421998422397620497557942631772228552491146882785842882555772068583002473431556523621001640 (153 digits)
Mon Dec 28 23:15:05 2015  searching for 15-digit factors
Mon Dec 28 23:15:06 2015  P-1 stage 2 factor found
Mon Dec 28 23:15:06 2015  searching for 20-digit factors
Mon Dec 28 23:15:10 2015  searching for 25-digit factors
Mon Dec 28 23:15:42 2015  commencing quadratic sieve (90-digit input)
Mon Dec 28 23:15:42 2015  using multiplier of 5
Mon Dec 28 23:15:42 2015  using VC8 32kb sieve core
Mon Dec 28 23:15:42 2015  sieve interval: 36 blocks of size 32768
Mon Dec 28 23:15:42 2015  processing polynomials in batches of 6
Mon Dec 28 23:15:42 2015  using a sieve bound of 1615891 (61176 primes)
Mon Dec 28 23:15:42 2015  using large prime bound of 135734844 (27 bits)
Mon Dec 28 23:15:42 2015  using double large prime bound of 435355802910756 (42-49 bits)
Mon Dec 28 23:15:42 2015  using trial factoring cutoff of 49 bits
Mon Dec 28 23:15:42 2015  polynomial 'A' values have 12 factors
Tue Dec 29 00:59:17 2015  61618 relations (16187 full + 45431 combined from 670278 partial), need 61272
Tue Dec 29 00:59:18 2015  begin with 686465 relations
Tue Dec 29 00:59:18 2015  reduce to 151468 relations in 10 passes
Tue Dec 29 00:59:18 2015  attempting to read 151468 relations
Tue Dec 29 00:59:21 2015  recovered 151468 relations
Tue Dec 29 00:59:21 2015  recovered 132159 polynomials
Tue Dec 29 00:59:21 2015  attempting to build 61618 cycles
Tue Dec 29 00:59:21 2015  found 61618 cycles in 5 passes
Tue Dec 29 00:59:21 2015  distribution of cycle lengths:
Tue Dec 29 00:59:21 2015     length 1 : 16187
Tue Dec 29 00:59:21 2015     length 2 : 11572
Tue Dec 29 00:59:21 2015     length 3 : 10810
Tue Dec 29 00:59:21 2015     length 4 : 8256
Tue Dec 29 00:59:21 2015     length 5 : 5949
Tue Dec 29 00:59:21 2015     length 6 : 3804
Tue Dec 29 00:59:21 2015     length 7 : 2288
Tue Dec 29 00:59:21 2015     length 9+: 2752
Tue Dec 29 00:59:21 2015  largest cycle: 19 relations
Tue Dec 29 00:59:21 2015  matrix is 61176 x 61618 (15.9 MB) with weight 3685877 (59.82/col)
Tue Dec 29 00:59:21 2015  sparse part has weight 3685877 (59.82/col)
Tue Dec 29 00:59:22 2015  filtering completed in 3 passes
Tue Dec 29 00:59:22 2015  matrix is 57454 x 57518 (14.9 MB) with weight 3452460 (60.02/col)
Tue Dec 29 00:59:22 2015  sparse part has weight 3452460 (60.02/col)
Tue Dec 29 00:59:22 2015  saving the first 48 matrix rows for later
Tue Dec 29 00:59:22 2015  matrix includes 64 packed rows
Tue Dec 29 00:59:22 2015  matrix is 57406 x 57518 (9.5 MB) with weight 2692576 (46.81/col)
Tue Dec 29 00:59:22 2015  sparse part has weight 1917967 (33.35/col)
Tue Dec 29 00:59:22 2015  using block size 8192 and superblock size 589824 for processor cache size 6144 kB
Tue Dec 29 00:59:22 2015  commencing Lanczos iteration
Tue Dec 29 00:59:22 2015  memory use: 6.0 MB

**Comment by VirusD** [comment] 2015-12-29 00:07
LoL. My thread just totally got hijacked.
msalvini, if you still need help, please head on over to http://www.bleepingcomputer.com/news/security/new-telsacrypt-version-adds-the-vvv-extension-to-encrypted-files/#cid583
Several people there are helping others in need, myself included.

Can we please get back to the thread topic?

**Comment by VirusD** [comment] 2015-12-29 00:14
If the first file is damaged, OK.
Why is the second file I posted short a few characters?
Judging by the starting address, it seems to be in the correct spot, 0x00000108

**Comment by Googulator** [comment] 2015-12-29 01:49
First file is damaged. It probably got damaged _after_ it was encrypted by the virus, because the header is also missing.

The other files do in fact have short keys - however, there were a few bugs handling them. They should decrypt fine with my recently pushed changes.

Note that TeslaDecoder also has trouble with these files; specifically if you try to pass the AES key as returned by unfactor.py to TeslaDecoder, it will report success, but decrypt garbage. OTOH if you pass the "fixed" AES key to TeslaDecoder (see unfactor.py source, function fix_key), it will bail out with "incorrect key". TeslaDecoder decrypts these files properly if given the Bitcoin key, internally generating the correct "raw" and "fixed" AES keys, but won't properly accept either when the AES key is given directly.

EDIT: Just to clarify; the AES public key is 1 byte short in the 2 sample files, because the randomly-generated AES private key happened to begin with a NUL byte. This is not a display bug, the AES public key really is two hex digits shorter than usual. Regardless of this, the most recent version of TeslaCrack should decrypt such files correctly.

**Comment by Googulator** [comment] 2015-12-29 02:15
@msalvini: "Msieve v. 1.52 (SVN 939)" is known to be buggy, crashing in the linear algebra stage. Use another build, or try YAFU.

**Comment by martinaovivo** [comment] 2015-12-29 12:15
@VirusD I checked your file and is OK.

pippo.zip

C:\pippo>teslacrack.py
Cannot decrypt ./Gita - M di Campiglio 003.JPG.vvv, unknown key
Cannot decrypt ./lettera Prefetto.pdf.vvv, unknown key
Software has encountered the following unknown AES keys, please crack them first using msieve:
0107802EC44DADB6B4B377C108BF4BE4F28F8D5A6E3CE6CC442FF2902B0E2B88F4572E69F7BCED290E04441E11153E1A517BBF40B9354DD87BE036D68FA01E found in ./Gita - M di Campiglio 003.JPG.vvv
Alternatively, you can crack the following Bitcoin key(s) using msieve, and use them with TeslaDecoder:
01125E3BFB9319CF409D3B48335458974676DF5149501AAF60725F559D5C75B514DA2AF49D5A5763E0E8E05706E2F63D21CBBE0B19BFE979569114CB2638DA7E found in ./Gita - M di Campiglio 003.JPG.vvv

C:\pippo>

C:\tesla\yafu-1.34>yafu-x64.exe "factor(0x0107802EC44DADB6B4B377C108BF4BE4F28F8D5A6E3CE6CC442FF2902B0E2B88F4572E69F7BCED290E04441E11153E1A517BBF40B9354DD87BE036D68FA01E)" -threads 16

fac: factoring 210581240500046030184183115465365828581079991578833237829037324100395658941560446260372510036077400413489724844040082195975002929902810273225208995870
fac: using pretesting plan: normal
fac: using tune info for qs/gnfs crossover
div: primes less than 10000
fmt: 1000000 iterations
rho: x^2 + 3, starting 1000 iterations on C149
rho: x^2 + 2, starting 1000 iterations on C149
rho: x^2 + 2, starting 1000 iterations on C142
rho: x^2 + 1, starting 1000 iterations on C142
pm1: starting B1 = 150K, B2 = gmp-ecm default on C142
ecm: 30/30 curves on C142, B1=2K, B2=gmp-ecm default
ecm: 74/74 curves on C142, B1=11K, B2=gmp-ecm default
ecm: 224/224 curves on C142, B1=50K, B2=gmp-ecm default, ETA: 2 sec
pm1: starting B1 = 3750K, B2 = gmp-ecm default on C142
ecm: 288/432 curves on C142, B1=250K, B2=gmp-ecm default, ETA: 1.2 min
ecm: 112/128 curves on C113, B1=250K, B2=gmp-ecm default, ETA: 8 sec

starting SIQS on c75: 791517818189570106050970322706147237598888357260514195744948688323190256057

==== sieving in progress (16 threads):   27680 relations needed ====
====            Press ctrl-c to abort and save state            ====
30212 rels found: 15659 full + 14553 from 146542 partial, (9941.18 rels/sec)

SIQS elapsed time = 17.3058 seconds.
Total factoring time = 223.5448 seconds

**_factors found**_

P1 = 2
P1 = 5
P7 = 9466381
P29 = 37325120299798727813062749491
P38 = 75296326354111835743743187328514161821
P29 = 50006315896415979575302726007
P47 = 15828356958531697406641930783028239095850947151

ans = 1

C:\pippo>unfactor.py "lettera Prefetto.pdf.vvv" 2 5 9466381 37325120299798727813062749491 75296326354111835743743187328514161821 50006315896415979575302726007 15828356958531697406641930783028239095850947151
Candidate AES private key: b'\x00\x14\x2c\x71\xd9\x9d\xe2\xba\xde\x94\xad\xb7\xc2\x90\x5e\x94\x84\x9a\xca\x34\x49\xf7\xe0\xd9\x4d\xb5\xa3\x39\x5d\xca\x67\xbf' (00142C71D99DE2BADE94ADB7C2905E94849ACA3449F7E0D94DB5A3395DCA67BF)

Edit teslacrack.py, and add your public and private AES keys to the known_keys array.
'0107802EC44DADB6B4B377C108BF4BE4F28F8D5A6E3CE6CC442FF2902B0E2B88F4572E69F7BCED290E04441E11153E1A517BBF40B9354DD87BE036D68FA01E': b'\x00\x14\x2c\x71\xd9\x9d\xe2\xba\xde\x94\xad\xb7\xc2\x90\x5e\x94\x84\x9a\xca\x34\x49\xf7\xe0\xd9\x4d\xb5\xa3\x39\x5d\xca\x67\xbf',

C:\pippo>teslacrack.py
Decrypting ./Gita - M di Campiglio 003.JPG.vvv
Decrypting ./lettera Prefetto.pdf.vvv

C:\pippo>

**Comment by martinaovivo** [comment] 2015-12-29 12:21
@msalvini 

C:\tesla\yafu-1.34>yafu-x64.exe "factor(0x097AE3032C33E55B89202DF8933FAAB54A5B411381626C84C9CD5CED79250FEA43FB2969C5174A146D8F62DE91FD8B2B5FAE21857C6D79A34438A06976F2A9A8)" -threads 16

fac: factoring 496509271878276672974271271553423839120365806755336402269183599421998422397620497557942631772228552491146882785842882555772068583002473431556523621001640
fac: using pretesting plan: normal
fac: using tune info for qs/gnfs crossover
div: primes less than 10000
fmt: 1000000 iterations
rho: x^2 + 3, starting 1000 iterations on C150
rho: x^2 + 2, starting 1000 iterations on C150
rho: x^2 + 2, starting 1000 iterations on C146
rho: x^2 + 1, starting 1000 iterations on C146
pm1: starting B1 = 150K, B2 = gmp-ecm default on C146
ecm: 30/30 curves on C109, B1=2K, B2=gmp-ecm default
ecm: 74/74 curves on C109, B1=11K, B2=gmp-ecm default
ecm: 16/224 curves on C109, B1=50K, B2=gmp-ecm default, ETA: 16 sec
ecm: 48/192 curves on C90, B1=50K, B2=gmp-ecm default, ETA: 9 sec

starting SIQS on c67: 3709626167001736337298420806299957017413394840216154055556305292937

==== sieving in progress (16 threads):    8800 relations needed ====
====            Press ctrl-c to abort and save state            ====
9705 rels found: 4808 full + 4897 from 44499 partial, (16764.87 rels/sec)

SIQS elapsed time = 3.1673 seconds.
fac: factoring 5590937729563113656487246972058404727
fac: using pretesting plan: normal
fac: no tune info: using qs/gnfs crossover of 95 digits
div: primes less than 10000
fmt: 1000000 iterations
rho: x^2 + 3, starting 1000 iterations on C37
rho: x^2 + 2, starting 1000 iterations on C37
rho: x^2 + 1, starting 1000 iterations on C37
pm1: starting B1 = 150K, B2 = gmp-ecm default on C37
ecm: 0/30 curves on C37, B1=2K, B2=gmp-ecm default
ecm: 0/29 curves on C28, B1=2K, B2=gmp-ecm default
ecm: 0/28 curves on C20, B1=2K, B2=gmp-ecm default
Total factoring time = 0.0881 seconds
Total factoring time = 12.3654 seconds

**_factors found**_

P1 = 2
P1 = 2
P1 = 2
P1 = 5
P2 = 31
P5 = 37831
P19 = 2772153293990551087
P24 = 184088141326110274201337
P35 = 16744995996172986775404837212112061
P33 = 221536402149606908120742381353917
P10 = 4813386163
P8 = 44842591
P8 = 46563263
P12 = 556288196813

ans = 1

**Comment by msalvini** [comment] 2015-12-29 13:41
For. martinaovivo

python unfactor.py cipas.doc.vvv 2 2 2 5 31 37831 2772153293990551087 184088141326110274201337 16744995996172986775404837212112061 221536402149606908120742381353917 4813386163 44842591 46563263 556288196813

by executing me back to the command prompt but it does not give me the private key error it ! maybe the problem is now my computer I can post my files .vvv ?

**Comment by msalvini** [comment] 2015-12-29 13:52
This is the result of msieve the problem is that giving the command unfactor.py me back to the prompt and does not give me any key private !! I do not know where I'm wrong

C:\TeslaCrack>msieve -v -e 0x097AE3032C33E55B89202DF8933FAAB54A5B411381626C84C9C
D5CED79250FEA43FB2969C5174A146D8F62DE91FD8B2B5FAE21857C6D79A34438A06976F2A9A8

Msieve v. 1.52 (SVN 883 pre-release)
Tue Dec 29 12:56:30 2015
random seeds: 12dd83c8 1e1efff3
factoring 4965092718782766729742712715534238391203658067553364022691835994219984
22397620497557942631772228552491146882785842882555772068583002473431556523621001
640 (153 digits)
searching for 15-digit factors
ECM stage 1 factor found
searching for 20-digit factors
ECM stage 1 factor found
searching for 25-digit factors
200 of 214 curves
completed 214 ECM curves
commencing quadratic sieve (90-digit input)
using multiplier of 5
using VC8 32kb sieve core
sieve interval: 36 blocks of size 32768
processing polynomials in batches of 6
using a sieve bound of 1615891 (61176 primes)
using large prime bound of 135734844 (27 bits)
using double large prime bound of 435355802910756 (42-49 bits)
using trial factoring cutoff of 49 bits
polynomial 'A' values have 12 factors

sieving in progress (press Ctrl-C to pause)
61285 relations (16033 full + 45252 combined from 670798 partial), need 61272
61285 relations (16033 full + 45252 combined from 670798 partial), need 61272
sieving complete, commencing postprocessing
begin with 686831 relations
reduce to 150478 relations in 9 passes
attempting to read 150478 relations
recovered 150478 relations
recovered 131500 polynomials
attempting to build 61285 cycles
found 61285 cycles in 5 passes
distribution of cycle lengths:
   length 1 : 16033
   length 2 : 11735
   length 3 : 10853
   length 4 : 8240
   length 5 : 5722
   length 6 : 3740
   length 7 : 2283
   length 9+: 2679
largest cycle: 18 relations
matrix is 61176 x 61285 (15.8 MB) with weight 3650759 (59.57/col)
sparse part has weight 3650759 (59.57/col)
filtering completed in 3 passes
matrix is 57488 x 57552 (14.9 MB) with weight 3458479 (60.09/col)
sparse part has weight 3458479 (60.09/col)
saving the first 48 matrix rows for later
matrix includes 64 packed rows
matrix is 57440 x 57552 (9.5 MB) with weight 2692124 (46.78/col)
sparse part has weight 1919570 (33.35/col)
using block size 22976 for processor cache size 6144 kB
commencing Lanczos iteration
memory use: 5.9 MB
lanczos halted after 909 iterations (dim = 57437)
recovered 17 nontrivial dependencies
p1 factor: 2
p1 factor: 2
p1 factor: 2
p1 factor: 5
p2 factor: 31
p5 factor: 37831
p8 factor: 44842591
p8 factor: 46563263
p10 factor: 4813386163
prp12 factor: 556288196813
prp19 factor: 2772153293990551087
prp24 factor: 184088141326110274201337
prp33 factor: 221536402149606908120742381353917
prp35 factor: 16744995996172986775404837212112061

**Comment by martinaovivo** [comment] 2015-12-29 13:52
@msalvini

If not effect with unfactor.py you should use the unfactor-ecdsa.py .

Yes , send your files I test the key.

Edit: Did you find the same factors . :)

Edit: Post any encrypted vvv file

**Comment by msalvini** [comment] 2015-12-29 13:56
I'm sorry as you send a file from here ! :))

**Comment by msalvini** [comment] 2015-12-29 14:21
ok, everything works thanks to everyone one last thing as I can remove automatically after the command teslacral.py files ending .vvv?

**Comment by martinaovivo** [comment] 2015-12-29 14:27
After checking the files, you can search for \* .vvv on windows and remove. Or, create a batch file with the command del / s \* .vvv
Sorry if there is any error in writing, but in some parts I use the translator.

**Comment by msalvini** [comment] 2015-12-29 14:34
ok

**Comment by Googulator** [comment] 2015-12-29 15:19
There is also a --delete option in teslacrack.py. It will only delete vvv files that it did actually decrypt - so ones with an unknown key, or where a file with the name of the decrypted file already exists, will be left behind for future analysis.

**Comment by Googulator** [comment] 2015-12-29 20:58
Closing. All issues discussed in this ticket appear to be solved now.

**Closed as completed by Googulator** 2015-12-29 20:58 UTC
